### ISSUE TITLE
D7.1.1 Dissemination Plan

### ISSUE THREAD

**Issue by ferhaterata** [ModelWriter/Project-Management#109]
- [ ] #116 [OBEO] Project website
- [ ] #120 [UNIT] LinkedIn group
- [ ] #121 [UNIT] Twitter group
- [ ] #133 [OBEO+UNIT] Product website
- [x] #134 [OBEO+ALL] Product Forum

**Comment by mrostren** [comment]
We have started writing the Dissemination Plan.

For this aim we have initialized a list of actions to do.
We need your contribution so please add your additional actions, complete or comment the existing.

You find the list of actions and the dissemination plan report on google drive in the WP7 repository: 
https://drive.google.com/?usp=folder&authuser=0#folders/0B115qHHFY_rua2NQOFVHREx0RlU

Regards

**Comment by ferhaterata** [comment]
Hi Marwa,

You are supposed to create new sub tasks and deliverables at WP7 (its own repository). This repository (project management) only includes the deliverables that we submitted in the FPP.

So, I suggest to move the last two deliverables "[OBEO+UNIT] Product website" and "[OBEO+ALL] Product Forum" under WP7.

On the other hand, we can state these deliverables as part of deliverable list of WP7 in the FPP. But we need to submit another CR for this.

What is your opinion?

/CC @m-challenger

**Comment by mrostren** [comment]
Hello Ferhat, Sorry for the mess, yes of course the specific new tasks must be under the WP7 but partners are filtering the list in the Project-Management so they will not see this tasks easily..
is their any other solution ?

PS: There is no need to make a CR for this, the dissemination plan objective is to define actions TODO during the project life cycle and may change frequently ...
